arb-dir: l10n
format: true
nullable-getter: false
output-class: AppLocalizations
output-dir: lib/app/l10n
output-localization-file: localizations.dart
preferred-supported-locales: [ es, en ]
template-arb-file: app_es.arb
untranslated-messages-file: l10n/untranslated_messages.json
use-escaping: true
use-named-parameters: true
